# Generated by Django 6.0.5 on 2026-06-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsnovnaSkola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okrug', models.CharField(max_length=160)),
                ('opstina', models.CharField(max_length=120)),
                ('naziv', models.CharField(max_length=220)),
                ('mesto', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocoded_query', models.CharField(blank=True, max_length=300)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['opstina', 'naziv'],
                'constraints': [models.UniqueConstraint(fields=('okrug', 'opstina', 'naziv'), name='unique_osnovna_skola')],
            },
        ),
        migrations.CreateModel(
            name='RezultatSkole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skolska_godina', models.CharField(max_length=20)),
                ('broj_ucenika', models.PositiveIntegerField(default=0)),
                ('prosek_6', models.FloatField(blank=True, null=True)),
                ('prosek_7', models.FloatField(blank=True, null=True)),
                ('prosek_8', models.FloatField(blank=True, null=True)),
                ('prosek_bodova_os', models.FloatField(blank=True, null=True)),
                ('prosek_zavrsni', models.FloatField(blank=True, null=True)),
                ('ukupno_poena', models.FloatField(blank=True, null=True)),
                ('skola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezultati', to='vizualizacija.osnovnaskola')),
            ],
            options={
                'ordering': ['-skolska_godina', 'skola__naziv'],
                'constraints': [models.UniqueConstraint(fields=('skola', 'skolska_godina'), name='unique_rezultat_skole_po_godini')],
            },
        ),
    ]
